version: "3.9"

services:
  api:
    restart: always
    build:
      context: ./api
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - ./api:/app/
      - /app/.venv/
    depends_on:
      db:
        condition: service_healthy
    environment:
      DJANGO_SUPERUSER_EMAIL: su@gmail.com
      DJANGO_SUPERUSER_PASSWORD: su
      POSTGRES_DB: trading
      POSTGRES_USER: trading
      POSTGRES_PASSWORD: trading
  db:
    restart: always
    image: postgres:16.4
    environment:
      POSTGRES_USER: trading
      POSTGRES_PASSWORD: trading
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  pg_data:
